apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  generateName: build-deploy-
spec:
  pipelineRef:
    name: build-and-deploy
  params:
  - name: deployment-name
    value: node-example
  - name: git-url
    value: https://github.com/odrodrig/nodejs-example.git
  - name: IMAGE
    value: core.oliver-openshift-4-5-2bef1f4b4097001da9502000c44fc2b2-0000.us-east.containers.appdomain.cloud/library/nodejs-example:3
  workspaces:
  - name: shared-workspace
    volumeClaimTemplate:
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 500Mi
  # serviceAccountName: pipeline